Repository langchain-ai/langgraph, pull requests merged in 2025-06, with the labels that each got.

#4893 Remove add_conditional_edge(..., then=)
  libs/langgraph/langgraph/channels/dynamic_barrier_value.py
  libs/langgraph/langgraph/graph/branch.py
  libs/langgraph/langgraph/graph/state.py
  libs/langgraph/tests/__snapshots__/test_large_cases.ambr
  libs/langgraph/tests/__snapshots__/test_pregel.ambr
  libs/langgraph/tests/test_large_cases.py
  libs/langgraph/tests/test_large_cases_async.py
  libs/langgraph/tests/test_pregel.py
  libs/langgraph/tests/test_pregel_async.py
Labels: v1

#4932 Improve type checking on graph `init` and `invoke`/`stream`
  .gitignore
  libs/langgraph/langgraph/graph/state.py
  libs/langgraph/langgraph/pregel/__init__.py
  libs/langgraph/langgraph/pregel/protocol.py
  libs/langgraph/langgraph/typing.py
  libs/langgraph/tests/test_state.py
  libs/langgraph/tests/test_type_checking.py
Labels: v1

#4946 Fix duplicate article typos in docs
  docs/docs/concepts/functional_api.md
  docs/docs/concepts/persistence.md
  docs/docs/how-tos/auth/custom_auth.md
  docs/docs/how-tos/multi-agent-multi-turn-convo-functional.ipynb
  docs/docs/tutorials/reflection/reflection.ipynb
Labels: codex

#4949 Fix async callback manager tag handling
  libs/langgraph/langgraph/utils/config.py
  libs/langgraph/tests/test_config_async.py
Labels: codex

#4983 deprecate `input` and `output` in favor of `input_schema` and `output_schema`
  docs/docs/concepts/low_level.md
  docs/docs/concepts/server-mcp.md
  docs/docs/how-tos/graph-api.ipynb
  libs/langgraph/bench/fanout_to_subgraph.py
  libs/langgraph/langgraph/_typing.py
  libs/langgraph/langgraph/func/__init__.py
  libs/langgraph/langgraph/graph/state.py
  libs/langgraph/langgraph/pregel/__init__.py
  libs/langgraph/langgraph/pregel/protocol.py
  libs/langgraph/tests/test_deprecation.py
  libs/langgraph/tests/test_large_cases.py
  libs/langgraph/tests/test_pregel.py
  libs/langgraph/tests/test_pregel_async.py
  libs/langgraph/tests/test_state.py
  libs/langgraph/tests/test_type_checking.py
  libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py
Labels: v1

#5035 Support numpy array serialization in JsonPlusSerializer
  docs/uv.lock
  libs/checkpoint-postgres/uv.lock
  libs/checkpoint-sqlite/uv.lock
  libs/checkpoint/langgraph/checkpoint/serde/jsonplus.py
  libs/checkpoint/langgraph/store/memory/__init__.py
  libs/checkpoint/pyproject.toml
  libs/checkpoint/tests/test_jsonplus.py
  libs/checkpoint/uv.lock
  libs/langgraph/uv.lock
  libs/prebuilt/uv.lock
Labels: codex

#5065 docs: fix langgraph docs
  docs/docs/cloud/deployment/self_hosted_control_plane.md
Labels: documentation

#5076 docs: added studio evals images
  docs/docs/cloud/how-tos/studio/run_evals.md
Labels: documentation
