Repository langchain-ai/langgraph, pull requests merged in 2025-07, with the labels that each got.

#5304 Update use_stream_react.md
  docs/docs/cloud/how-tos/use_stream_react.md
Labels: documentation

#5320 Adding disable_webhook to cli docs
  docs/docs/cloud/reference/cli.md
Labels: documentation

#5353 docs: update case studies
  docs/docs/adopters.md
Labels: documentation

#5377 docs: correct link in docs/docs/how-tos/graph-api.md
  docs/docs/how-tos/graph-api.md
Labels: documentation

#5329 docs: fix typo in persistence
  docs/docs/concepts/persistence.md
Labels: documentation

#5257 Updated examples for SummarizationNode to account for serde with persistence layers
  docs/docs/how-tos/memory/add-memory.md
Labels: documentation

#5413 docs: Add `RESUMABLE_STREAM_TTL_SECONDS` to env vars list
  docs/docs/cloud/reference/env_var.md
Labels: documentation

#5571 fix(docs): Change of condition arguments in Command API example for ease of reading.
  docs/docs/how-tos/graph-api.md
Labels: documentation

#5489 fix(docs): jokes needs reducer in graph-api.md (#5489)
  docs/docs/how-tos/graph-api.md
Labels: documentation

#5577 chore(docs): Migrate from pyautogen to ag2 Library
  docs/docs/how-tos/autogen-integration.md
Labels: dependencies

#5608 fix(docs): use InMemorySaver instead of `MemorySaver`
  docs/docs/concepts/durable_execution.md
  docs/docs/concepts/functional_api.md
  docs/docs/concepts/persistence.md
  docs/docs/how-tos/autogen-integration-functional.ipynb
  docs/docs/how-tos/autogen-integration.md
  docs/docs/how-tos/cross-thread-persistence-functional.ipynb
  docs/docs/how-tos/human_in_the_loop/add-human-in-the-loop.md
  docs/docs/how-tos/human_in_the_loop/wait-user-input.ipynb
  docs/docs/how-tos/multi-agent-multi-turn-convo-functional.ipynb
  docs/docs/how-tos/multi_agent.md
  docs/docs/how-tos/persistence-functional.ipynb
  docs/docs/how-tos/react-agent-from-scratch-functional.ipynb
  docs/docs/how-tos/use-functional-api.md
  docs/docs/tutorials/chatbots/information-gather-prompting.ipynb
  docs/docs/tutorials/customer-support/customer-support.ipynb
  docs/docs/tutorials/get-started/3-add-memory.md
  docs/docs/tutorials/get-started/4-human-in-the-loop.md
  docs/docs/tutorials/get-started/5-customize-state.md
  docs/docs/tutorials/get-started/6-time-travel.md
  docs/docs/tutorials/langgraph-platform/local-server.md
  docs/docs/tutorials/reflection/reflection.ipynb
  docs/docs/tutorials/tot/tot.ipynb
  docs/docs/tutorials/usaco/usaco.ipynb
  examples/code_assistant/langgraph_code_assistant_mistral.ipynb
  libs/checkpoint/README.md
  libs/checkpoint/tests/test_memory.py
  libs/langgraph/bench/__main__.py
  libs/langgraph/bench/fanout_to_subgraph.py
  libs/langgraph/bench/pydantic_state.py
  libs/langgraph/bench/react_agent.py
  libs/langgraph/bench/wide_dict.py
  libs/langgraph/bench/wide_state.py
  libs/langgraph/langgraph/func/__init__.py
  libs/langgraph/langgraph/graph/state.py
  libs/langgraph/langgraph/types.py
  libs/langgraph/tests/test_remote_graph.py
Labels: documentation

#5623 docs: more thorough notes on v0.6 features and changes
  docs/docs/concepts/human_in_the_loop.md
  docs/docs/reference/runtime.md
  docs/mkdocs.yml
  libs/langgraph/langgraph/func/__init__.py
  libs/langgraph/langgraph/graph/state.py
  libs/langgraph/langgraph/pregel/main.py
  libs/langgraph/langgraph/runtime.py
  libs/langgraph/langgraph/types.py
  libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py
Labels: documentation

#5477 fix(docs): Add missing imports to make examples runnable
  docs/docs/how-tos/memory/add-memory.md
  docs/docs/how-tos/tool-calling.md
  libs/langgraph/langgraph/func/__init__.py
Labels: awaiting author revision
